[JENKINS-70808] Fix isRestartable by only checking against the curren…
jenkinsci/blueocean-plugin pull request #2415
Opened 2023-03-16 06:43 UTC by Dohbedoh

…t node

# Description

See [JENKINS-70808](https://issues.jenkins.io/browse/JENKINS-70808).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

2023-03-16 06:48 UTC, Dohbedoh commented
cc @olamy

2023-03-16 06:48 UTC, olamy commented
see https://github.com/jenkinsci/blueocean-plugin/pull/2414 this will store the result for future use and so will be faster

2023-03-16 06:57 UTC, olamy requested changes

2023-03-16 06:57 UTC, olamy commented on blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
> +            this.run.getAction( RestartDeclarativePipelineAction.class );
this.run cannot work anymore here need to use `getRun()`

2023-03-16 06:57 UTC, olamy commented on blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
> +        FlowExecutionOwner owner = ((FlowExecutionOwner.Executable) run).asFlowExecutionOwner();
this.run cannot work anymore here need to use `getRun()`

2023-03-16 06:57 UTC, olamy commented on blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeImpl.java
> +            ExecutionModelAction execAction = run.getAction(ExecutionModelAction.class);
this.run cannot work anymore here need to use `getRun()`

2023-03-16 07:40 UTC, olamy commented
definitely computation need to be done in the constructor as the PR #2414 
because of this https://github.com/jenkinsci/blueocean-plugin/blob/95279d395af65b0ce545396dd530107873134a87/blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/PipelineNodeContainerImpl.java#L35 
until the job is finished `PipelineNodeContainerImpl` objects are rebuild.

2023-03-17 01:01 UTC, olamy commented
would be good to delete this PR and just finish this one first https://github.com/jenkinsci/blueocean-plugin/pull/2416 
then we merge it to master

2023-03-17 03:15 UTC, olamy commented
done via cherrrypick of the commit from the branch https://github.com/jenkinsci/blueocean-plugin/pull/2417

2023-03-17 04:26 UTC, olamy commented
done via https://github.com/jenkinsci/blueocean-plugin/commit/c284612ec2bcae03f247d24e5eab1ae535737ef0

2023-03-17 04:26 UTC, closed without merging